version: '3.8'

services:
    python:
        build: .
        working_dir: /app
        volumes:
            - type: bind
              source : ".."
              target : "/app"
        command: sleep infinity
